### PR TITLE
update `ExecutionTrace` to latest `TraceTable` struct in README example

### PR DESCRIPTION
**Pull request by bajpai244**
As per the latest v0.3.0, the struct `ExecutionTrace` must be replaced
with `TraceTable` in the example of the README.md file.

The PR updates the example and will make the example consistent with the latest v0.3.0 of Winterfell.

### CODE REVIEW

**Comment by bajpai244** [comment]
just signed the CLA! I guess the PR will be tagged soon!

**Comment by bajpai244** [comment]
@irakliyk it can be amazing if u can take a look at this PR!

**Comment by bajpai244** [comment]
Oh, yeah that was committed by mistake, I have removed the file from this PR 🙌

**Comment by bajpai244** [comment]
@irakliyk any idea why the last test failed? It seems to be emerging from a file that I have not committed in this PR.

**Comment by irakliyk** [comment]
This is probably because some formatting rules changed in Rust nightly recently. I know it's not related to this PR - but would you be able to fix it? Here is the error message:

```
error: writing `&mut Vec` instead of `&mut [_]` involves a new object where a slice will do
Error:    --> prover/src/composer/mod.rs:251:32
    |
251 | fn acc_poly<B, E>(accumulator: &mut Vec<E>, poly: &[B], value: E, k: E)
    |                                ^^^^^^^^^^^ help: change this to: `&mut [E]`
    |
    = note: `-D clippy::ptr-arg` implied by `-D clippy::all`
    = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#ptr_arg
```

**Comment by bajpai244** [comment]
Hey @irakliyk, I was away from the keyboard for some time, can we accept this PR first, and then I can make a separate PR for the other one ( would have to take out some time to check that out )?

I guess the update on README is necessary as the example there is not consistent with the current version of Winterfell. Have a nice day!

**Comment by bajpai244** [comment]
@irakliyk any updates?

**Comment by irakliyk** [comment]
@bajpai244 - sorry for the the delay! Could you rebase from main? Once you do that, I believe all the tests will pass and we can merge then.

**Comment by irakliyk** [comment]
I believe this was fixed as a part of #86

**Pull request closed without merging**
